# go2rtc 独立配置
# 负责接入小米摄像头并提供 RTSP 流给 Frigate
# 首次使用请打开 WebUI (http://localhost:1984) -> Add -> Xiaomi 登录

streams:
  study_cam:
    - xiaomi://1280623889:cn@192.168.31.9?did=268058994&model=chuangmi.camera.ipc021
  living_room_cam:
    - xiaomi://1280623889:cn@192.168.31.93?did=1148853409&model=chuangmi.camera.039c01

xiaomi:
  "1280623889": V1:pwROAesIuzMBPe5slLSsQu4sz3PH1kCVEf0dYLrn6a6OZMggIZuXgjKhM7UMo16HAJ+rfdszmunEwGohZ9Q8+Fn2xpbtBUqlcp4fJBEGFdKRwgJqB7RRHAuA17PutmIPyqtUI7X3D9xkeOZAoBdJ5aqGM8B/bo4zRuJY3UfPiDzqOCCngah6DxHI2gXBMsxsvd89OcGolrJh03yEFWPGZ/6pcjuR7W4wQuE0dG/bDQqWyO98LrEF87+rOVIWZdRsrAtwDwNqdhvthw3dEypWkjT9bFljclYOilUnBwRHxW96x8v5/aiPY/VdL9roG6Dzf3iJq8Xu5+LWKnS69icUXQ==
