# go2rtc 独立配置
# 负责接入小米摄像头并提供 RTSP 流给 Frigate
# 首次使用请打开 WebUI (http://localhost:1984) -> Add -> Xiaomi 登录

streams:
  study_cam:
    - xiaomi://1280623889:cn@192.168.31.9?did=268058994&model=chuangmi.camera.ipc021
  living_room_cam:
    - xiaomi://1280623889:cn@192.168.31.93?did=1148853409&model=chuangmi.camera.039c01

xiaomi:
  "1280623889": V1:pwROAesIuzMBPe5slLSsQg/diyBlHiK4ffQStX3kn/xtIyMsemiUNf40U+oz45QS6t9ffY7bGsOuXWQcmzt9rNy2zodLLjHHw1Udy4Jm6jWrYVrSht9qi54BQbEBwFGy3YFk1dxfOCDXhvxvyOTvaSk1DwNeFjOWhBJ5dTNufeZiNKgHx8dcrsYwhfGIZTzbPWGq6FAY1zFYi+uvcfsGUKAdeIj6qP2UssOguFFteN3lykkXpi7Pp7xb/WgvW0ppFmnu8gI1zpKF6Wm/rxS3z5DYOueVNxHc3NEqzzn8qLMqZYkvgFmG8L6m8B1nwF7UugQqcnS5CP1BH8hYEqYjVA==
